### ISSUE TITLE
Vault endpoint is not working

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#225] opened 2020-03-26 16:03 UTC
Currently the Vault endpoint (10.0.3.8:443) triggers this error when accessed through Chrome in Bastion host:

_**This page isn’t working**
10.0.3.8 sent an invalid response.
ERR_INVALID_HTTP_RESPONSE_

Whereas if an nonexistent URL is being loaded the error will be different:

_**This site can’t be reached**
10.0.3.7 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED_

**Comment by bimalgrewal** [comment] 2020-04-07 15:46
Unable to reproduce this bug. Deployed TB from master on 06/04 and was able to access Vault.

**Comment by oscarmon7** [comment] 2020-04-08 13:37
Did you use the tb-config-creator?

**Comment by scottholmangft** [comment] 2020-04-21 16:45
@bimalgrewal can we close this issue?

**Comment by bimalgrewal** [comment] 2020-04-22 14:01
@oscarmon7 Nope, I have updated my comment above.
@scottholmangft We need to keep this open.

**Comment by connor-mcshane** [comment] 2020-05-05 20:55
There are some bash scripts that are embedded deep within the main.tf 

I think its something around this, we probably should take these sorts of scripts out as they give off a bit of code smell.

![image](https://user-images.githubusercontent.com/10451364/81115164-2e2fe080-8f1b-11ea-9174-c5d5c7971681.png)

**Closed** 2020-05-12 23:04 UTC
Labels: bug, priority:high

**Comment by bimalgrewal** [comment] 2020-05-13 02:24
The Error is `MountVolume.SetUp failed for volume "vault-tls" : secret "vault-tls" not found`.
